// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SingularSystems.ProductOrderApp.Data;

#nullable disable

namespace ProductOrderApp.Server.Migrations
{
    [DbContext(typeof(ModelDbContext))]
    [Migration("20250921035939_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SingularSystems.ProductOrderApp.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityTown")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("SingularSystems.ProductOrderApp.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SingularSystems.ProductOrderApp.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SingularSystems.ProductOrderApp.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ImageUrl = "https://res.cloudinary.com/dvxz4yf0l/image/upload/v1758420464/airpods_max_2024_blue_pdp_image_position_01__wwen_1.png_fynhc8.jpg",
                            ProductDescription = "Apple AirPods Max, latest 2024 model, stunning blue.",
                            ProductName = "AirPods Max",
                            ProductPrice = 12999.00m
                        },
                        new
                        {
                            ProductId = 2,
                            ImageUrl = "https://res.cloudinary.com/dvxz4yf0l/image/upload/v1758420464/apple_watch_series_11_42mm_gps_rose_gold_aluminum_sport_band_light_blush_pdp_image_position_1__wwen_zvxhlq.jpg",
                            ProductDescription = "Apple Watch Series 11 in elegant rose gold.",
                            ProductName = "Apple Watch Series 11",
                            ProductPrice = 9999.00m
                        },
                        new
                        {
                            ProductId = 3,
                            ImageUrl = "https://res.cloudinary.com/dvxz4yf0l/image/upload/v1758420465/cl_iphone_17_pro_cosmic_orange_pdp_image_position_1__wwen_a0zoer.jpg",
                            ProductDescription = "iPhone 17 Pro in cosmic orange finish.",
                            ProductName = "iPhone 17 Pro",
                            ProductPrice = 25999.00m
                        },
                        new
                        {
                            ProductId = 4,
                            ImageUrl = "https://res.cloudinary.com/dvxz4yf0l/image/upload/v1758420467/ipad_pro_11_m4_cellular_space_black_pdp_image_position_1b__wwen_1_1_1_1_1_1_1_1_1_1_3_u1tyrb.png",
                            ProductDescription = "iPad Pro in sleek space black.",
                            ProductName = "iPad Pro",
                            ProductPrice = 19999.00m
                        },
                        new
                        {
                            ProductId = 5,
                            ImageUrl = "https://res.cloudinary.com/dvxz4yf0l/image/upload/v1758420467/iphone_16_plus_white_pdp_image_position_1__wwen_1_1_1_yyjkna.png",
                            ProductDescription = "iPhone 16 Plus in pristine white.",
                            ProductName = "iPhone 16 Plus",
                            ProductPrice = 21999.99m
                        },
                        new
                        {
                            ProductId = 6,
                            ImageUrl = "https://res.cloudinary.com/dvxz4yf0l/image/upload/v1758420466/iphone_16_pro_white_titanium_pdp_image_position_1__gben_1_1_1_1_tlte9z.png",
                            ProductDescription = "iPhone 16 Pro in classic white.",
                            ProductName = "iPhone 16 Pro",
                            ProductPrice = 23999.99m
                        },
                        new
                        {
                            ProductId = 7,
                            ImageUrl = "https://res.cloudinary.com/dvxz4yf0l/image/upload/v1758420465/iphone_17_sage_pdp_image_position_1__wwen_ye5iqg.jpg",
                            ProductDescription = "iPhone 17 in stylish sage green.",
                            ProductName = "iPhone 17",
                            ProductPrice = 25999.99m
                        },
                        new
                        {
                            ProductId = 8,
                            ImageUrl = "https://res.cloudinary.com/dvxz4yf0l/image/upload/v1758420465/iphone_air_light_gold_pdp_image_position_1__wwen_vulaid.jpg",
                            ProductDescription = "iPhone Air with a light gold finish.",
                            ProductName = "iPhone Air",
                            ProductPrice = 17999.99m
                        },
                        new
                        {
                            ProductId = 9,
                            ImageUrl = "https://res.cloudinary.com/dvxz4yf0l/image/upload/v1758420466/macbook_air_13-in_m4_chip_silver_pure_front_screen__usen_1_1_1_kvqt28.jpg",
                            ProductDescription = "MacBook Air in silver, lightweight and powerful.",
                            ProductName = "MacBook Air",
                            ProductPrice = 24999.99m
                        },
                        new
                        {
                            ProductId = 10,
                            ImageUrl = "https://res.cloudinary.com/dvxz4yf0l/image/upload/v1758420467/macbook_pro_16-inch_m4_pro_or_max_chip_space_black_pdp_image_position_1__wwen_1_3_pzpp6i.png",
                            ProductDescription = "MacBook Pro in space black, high-performance laptop.",
                            ProductName = "MacBook Pro",
                            ProductPrice = 37999.00m
                        });
                });

            modelBuilder.Entity("SingularSystems.ProductOrderApp.Models.Order", b =>
                {
                    b.HasOne("SingularSystems.ProductOrderApp.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SingularSystems.ProductOrderApp.Models.OrderItem", b =>
                {
                    b.HasOne("SingularSystems.ProductOrderApp.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SingularSystems.ProductOrderApp.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
